<?php
/**
 *  @file
 *  SN Tracking
 */

// Add {{ jsonld }} to theme/base/html twig

function jsonld_preprocess_html(&$variables) {

  // Get Current Path
  $current_uri = \Drupal::request()->getRequestUri();

  // Get JSON-LD data from table
  $jsonld_query = db_select('jsonld', 't')
       ->fields('t', array('jsonld'))
       ->execute()
       ->fetchObject();

  $json_ld = json_decode($jsonld_query->jsonld);


  $added_jsonld = '';


      // Count how many pages
      $count = 1;
      while (1){
        $object = 'jsonld_page_' . $count . '_path';
          if (strlen($json_ld->{$object}) < 1) {
            break;
          }
        $count++;
      }
      $count = $count - 1;

  // Loop through Pages
  for ($i = 1; $i < $count; $i++) {

    $path = 'jsonld_page_' . $i . '_path';
    $service = 'jsonld_page_' . $i . '_servicetype';
    $category = 'jsonld_page_' . $i . '_category';

    if (isset($json_ld->$path)) {
      if ($json_ld->$path == $current_uri) {
         $added_jsonld = '<script type="application/ld+json">
                          {
                            "@context": "http://schema.org",
                            "@type": "Service",
                            "serviceType": "' . $json_ld->$service . '",
                            "category": "' . $json_ld->$category . '",
                            "provider": {
                              "@type": "Organization",
                              "name": "' . $json_ld->jsonld_name . '"
                            },
                            "areaServed": {
                              "@type": "Country",
                              "name": "USA"
                            }
                          }
                            </script>';
      }
    }
  }

  $variables['jsonld'] = \Drupal\Core\Render\Markup::create(
  '<script type="application/ld+json">
                                 {
                                   "@context": "http://schema.org",
                                   "@type": "Organization",
                                   "name": "' . $json_ld->jsonld_name . '",
                                   "url": "' . $json_ld->jsonld_url . '",
                                   "logo": "' . $json_ld->jsonld_logo . '",
                                   "telephone": "' . $json_ld->jsonld_telephone . '",
                                   "foundingDate": "' . $json_ld->jsonld_foundingdate . '",
                                   "address": {
                                     "@type": "PostalAddress",
                                     "streetAddress": "' .  $json_ld->jsonld_address_street . '",
                                     "addressLocality": "' . $json_ld->jsonld_address_locality . '",
                                     "addressRegion": "' . $json_ld->jsonld_address_region . '",
                                     "postalCode": "' . $json_ld->jsonld_address_postalcode . '",
                                     "addressCountry": {
                                      "@type": "Country",
                                      "name": "' . $json_ld->jsonld_address_country . '"
                                     }
                                   }
                                 }
  </script>' . $added_jsonld);

   return $variables;

}

